### PR TITLE
Update package.json

### PR DESCRIPTION
**Pull request by tkdphoenix**
I am attempting to pull your project in as a dependency for a Polymer 3 project, and I am getting the error "Can't install git+https://github.com/BrightspaceUI/dropdown.git#c92e77e58e5721f7d1e17a140248c934a2daca0a: Missing package version". 

Is there any plan to put this on NPM? Your docs say "install with Bower" which isn't an option for Polymer 3.

### CODE REVIEW

**Comment by dlockhart** [comment]
Hey @tkdphoenix -- yeah, sorry about that. We're in the process of completing the transition to Polymer 3 so things are in a bit of limbo. We're still figuring out the best way to keep the version in `package.json` automatically updated across our many projects as we continuously make updates, without manually needing to do it.

Could you reference it using the GitHub syntax, like this?
`"d2l-dropdown": "BrightspaceUI/dropdown#semver:^7"`

**Comment by tkdphoenix** [comment]
I tried this as well as @latest but it is still looking for a version. 

Joel Grissom 
(480) 267-6374

**Comment by dlockhart** [comment]
Hmm, so probably you're using Yarn? It seems to have trouble with missing versions.

@mdgbayly was in the process of adding in some scripts to keep our versions in sync -- Martin, where did that end up?

**Comment by tkdphoenix** [comment]
Actually I am installing with NPM. Once I cloned the repo and put it in my own repo I was able to add a version and perform ‘npm i d2l-dropdown’ and it worked. 

Joel Grissom 
(480) 267-6374

**Comment by dlockhart** [comment]
Version is now included in `package.json`.

**Pull request closed without merging**
